[build]
builder = "nixpacks"

[deploy]
startCommand = "python run.py"
healthcheckPath = "/login"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = { default = "8000" }
